name: nix build

on:
  push:
    branches:
      - master

jobs:

  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.eval-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - id: eval-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --accept-flake-config --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    concurrency:
      group: ${{ github.workflow }}.${{ github.event.pull_request.number || github.ref }}.${{ matrix.host }}
      cancel-in-progress: true

    steps:
      - uses: jlumbroso/free-disk-space@main

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            max-jobs = auto
            max-substitution-jobs = 128
            http-connections = 128

      - uses: cachix/cachix-action@v14
        with:
          name: joinemm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Build ${{ matrix.host }}
        run: nix run nixpkgs#nixos-rebuild -- build -v --accept-flake-config --flake ".#${{ matrix.host }}"
