name: build all hosts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            trusted-public-keys = nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://nix-gaming.cachix.org https://cache.nixos.org
            connect-timeout = 5
            system-features = nixos-test benchmark big-parallel kvm

      - uses: cachix/cachix-action@v14
        with:
          name: joinemm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run nix-fast-build
        run: |
          nix build .#nixosConfigurations.zeus.config.system.build.toplevel

