name: build all hosts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          swap-storage: false 

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - name: Run nix-fast-build
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: nix run github:Mic92/nix-fast-build -- --cachix-cache joinemm --no-nom --skip-cached
