name: nix flake check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://nix-gaming.cachix.org https://joinemm.cachix.org
            trusted-public-keys = cache.nixos.org:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-gaming.cachix.org:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= joinemm.cachix.org:aMZBO1baRjhaI5QzePLelFz/GJ82fZOjmiHQwCl1FxI= 

      - name: Run nix flake check 
        run: nix flake check -v
